# Generated by Django 4.2.3 on 2023-08-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Con',
        ),
    ]
